### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by akrejcir**
Executed:
```
go mod tidy
go mod vendor
```

### CODE REVIEW

**Comment by omeryahud** [comment]
This is to remove the dependencies added by  the cert rotation attempt?

**Comment by akrejcir** [comment]
No, they were added when vendoring was introduced by commit:
https://github.com/kubevirt/kubevirt-template-validator/commit/73b70cd38ed74d126d3cc97c72c610551aa9c023

It seems they are not needed anymore.

**Pull request merged**
